"""Registry Schema (FR-1) + loader. YAML files in data/registries/."""

from __future__ import annotations

from enum import Enum
from pathlib import Path

import yaml
from core_schema.errors import SchemaError
from pydantic import BaseModel, ConfigDict, field_validator


class OriginClass(str, Enum):
    OWN_HARBOR_RUN = "own_harbor_run"
    PUBLIC_TRAJECTORY_COLLECTION = "public_trajectory_collection"
    PUBLIC_CI_LOGS = "public_ci_logs"
    # Story 14.1 (2026-08-16): own-repo mutant task source — tasks generated by
    # the sealed mutant protocol inside a rights-owned repo (TS/vitest first).
    OWN_REPO_MUTANT_TASKS = "own_repo_mutant_tasks"


class SourceEntry(BaseModel):
    model_config = ConfigDict(extra="forbid")

    source_id: str
    origin_class: OriginClass
    license: str
    usage_rights: str
    covered_families: list[str]
    covered_generations: list[str]
    snapshot_content_hash: str
    coverage_gaps: list[str]
    source_version: int = 1
    registered_at: str  # occurrence metadata
    notes: str = ""
    supersedes: str | None = None

    @field_validator("snapshot_content_hash")
    @classmethod
    def _hash(cls, v: str) -> str:
        if len(v) != 64 or any(c not in "0123456789abcdef" for c in v.lower()):
            raise SchemaError(
                "LI-REGISTRY-001", "snapshot_content_hash must be sha256 hex", {"got": v}
            )
        return v.lower()  # normalized: audit comparisons are case-safe (EC-19)


def _entries_map(data: object) -> list[dict]:
    if not isinstance(data, dict):
        raise SchemaError("LI-REGISTRY-004", "registry root must be a mapping", {})
    sources = data.get("sources", [])
    if not isinstance(sources, list):
        raise SchemaError("LI-REGISTRY-004", "'sources' must be a list", {})
    return sources


def load_registry(path: Path) -> dict[str, SourceEntry]:
    raw = yaml.safe_load(Path(path).read_text())
    entries: dict[str, SourceEntry] = {}
    for row in _entries_map(raw):
        try:
            e = SourceEntry.model_validate(row)
        except SchemaError:
            raise
        except Exception as exc:
            raise SchemaError(
                "LI-REGISTRY-002", f"invalid source entry: {row.get('source_id', '?')}", {}
            ) from exc
        if e.source_id in entries:
            raise SchemaError("LI-REGISTRY-003", f"duplicate source_id {e.source_id}", {})
        entries[e.source_id] = e
    return entries


def audit_source(entry: SourceEntry, new_snapshot_hash: str) -> tuple[str, int, str]:
    """FR-1: detect upstream mutation and compute the bump consequence.
    Returns (verdict, new_source_version, note). 'mutated' bumps +1 and warns."""
    if entry.snapshot_content_hash == new_snapshot_hash.lower():
        return ("unchanged", entry.source_version, "")
    return (
        "mutated",
        entry.source_version + 1,
        f"WARN: upstream snapshot for {entry.source_id} mutated; re-ingestion must bump to v{entry.source_version + 1}",
    )
